# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../download_strategy"
class Cleo < Formula
  desc "Cleo CLI - do stuff faster"
  homepage "https://github.com/meetcleo/cleo-cli"
  version "1.61.0"

  depends_on "frpc"

  on_macos do
    on_intel do
      url "https://github.com/meetcleo/cleo-cli/releases/download/v1.61.0/cleo_1.61.0_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d82c3bb107c49039ebc7554cdedbd29257ae488ba2c01eee76694473ac0f5eee"

      def install
        bin.install "cleo"
        bash_completion.install "completions/cleo.bash" => "cleo"
        zsh_completion.install "completions/cleo.zsh" => "_cleo"
        fish_completion.install "completions/cleo.fish"
      end
    end
    on_arm do
      url "https://github.com/meetcleo/cleo-cli/releases/download/v1.61.0/cleo_1.61.0_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "ebef877fd9d7c14ace3fecc1383ff64b2db27038c847c8472beccf02cc0a690b"

      def install
        bin.install "cleo"
        bash_completion.install "completions/cleo.bash" => "cleo"
        zsh_completion.install "completions/cleo.zsh" => "_cleo"
        fish_completion.install "completions/cleo.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/meetcleo/cleo-cli/releases/download/v1.61.0/cleo_1.61.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "5374ed06509381f4acd9ef71cfa3a02a838e0ebf1c355915700581604701c83d"

        def install
          bin.install "cleo"
          bash_completion.install "completions/cleo.bash" => "cleo"
          zsh_completion.install "completions/cleo.zsh" => "_cleo"
          fish_completion.install "completions/cleo.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/meetcleo/cleo-cli/releases/download/v1.61.0/cleo_1.61.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "f2880c204fd327dd85c208ffae6866ddb559745d3c78885dee999c0704a64430"

        def install
          bin.install "cleo"
          bash_completion.install "completions/cleo.bash" => "cleo"
          zsh_completion.install "completions/cleo.zsh" => "_cleo"
          fish_completion.install "completions/cleo.fish"
        end
      end
    end
  end
end
