# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../download_strategy"
class Cleo < Formula
  desc "Cleo CLI - do stuff faster"
  homepage "https://github.com/meetcleo/cleo-cli"
  version "1.34.0"

  depends_on "frpc"

  on_macos do
    on_intel do
      url "https://github.com/meetcleo/cleo-cli/releases/download/v1.34.0/cleo_1.34.0_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "a8786de9761e8af51fdb7a16a397527d47b503543734f910e95f788b4e084a18"

      def install
        bin.install "cleo"
        bash_completion.install "completions/cleo.bash" => "cleo"
        zsh_completion.install "completions/cleo.zsh" => "_cleo"
        fish_completion.install "completions/cleo.fish"
      end
    end
    on_arm do
      url "https://github.com/meetcleo/cleo-cli/releases/download/v1.34.0/cleo_1.34.0_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1e4d306fd6f335c25959a957901a91eed76975182b887d3cf3ded8c2b3a1293c"

      def install
        bin.install "cleo"
        bash_completion.install "completions/cleo.bash" => "cleo"
        zsh_completion.install "completions/cleo.zsh" => "_cleo"
        fish_completion.install "completions/cleo.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/meetcleo/cleo-cli/releases/download/v1.34.0/cleo_1.34.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "104fd975100762e288c6aefe11201f6f032f0d72371b74d75f9776f42dd6d17e"

        def install
          bin.install "cleo"
          bash_completion.install "completions/cleo.bash" => "cleo"
          zsh_completion.install "completions/cleo.zsh" => "_cleo"
          fish_completion.install "completions/cleo.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/meetcleo/cleo-cli/releases/download/v1.34.0/cleo_1.34.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "6c6676627d59f17b33e217b26600c57d6431f249f4bbf6bc2c86927db979938f"

        def install
          bin.install "cleo"
          bash_completion.install "completions/cleo.bash" => "cleo"
          zsh_completion.install "completions/cleo.zsh" => "_cleo"
          fish_completion.install "completions/cleo.fish"
        end
      end
    end
  end
end
