# typed: false
# frozen_string_literal: true

# This file was generated by GitHub Actions. DO NOT EDIT.
require_relative "../download_strategy"

class CleoAgent < Formula
  desc "Cleo agent executable"
  homepage "https://github.com/meetcleo/cleo-agent"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/meetcleo/cleo-agent/releases/download/v0.1.0/cleo-agent_0.1.0_darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "6843f0d73aed45a7d4c8fec790b6f61a0d792cf1e71ad02f807528ce9232c5b7"

      def install
        bin.install "cleo-agent"
      end
    end

    on_arm do
      url "https://github.com/meetcleo/cleo-agent/releases/download/v0.1.0/cleo-agent_0.1.0_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "6e52a06d9233f977c118878c314a70af0cce846dfcae2ef59d7e74c2c05b3545"

      def install
        bin.install "cleo-agent"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/meetcleo/cleo-agent/releases/download/v0.1.0/cleo-agent_0.1.0_linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "98ddb1a9076fbd5ea1a96e4b3766307aa962cffcc3b6be4fba3db18b44a092e6"

        def install
          bin.install "cleo-agent"
        end
      end
    end
  end
end
