# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CleoCli < Formula
  desc "Cleo CLI - do stuff faster"
  homepage "https://github.com/meetcleo/homebrew-cleo"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meetcleo/cleo-cli/releases/download/v0.0.4/cleo-cli_0.0.4_darwin_amd64.tar.gz"
      sha256 "ca0009bef6c56b7f5740e8a07139cf439abac65fd6ac6c39b719cb2d408686ff"

      def install
        bin.install "cleo-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/meetcleo/cleo-cli/releases/download/v0.0.4/cleo-cli_0.0.4_linux_amd64.tar.gz"
      sha256 "3098a4c7eedc13cda00dfe8a85bb649cd1cb2d363b1f5b4a8818b4c987ed19f0"

      def install
        bin.install "cleo-cli"
      end
    end
  end
end
