# typed: false
# frozen_string_literal: true

# This file was generated by GitHub Actions. DO NOT EDIT.
require_relative "../download_strategy"

class CleoAgent < Formula
  desc "Cleo agent executable"
  homepage "https://github.com/meetcleo/cleo-agent"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/meetcleo/cleo-agent/releases/download/v0.1.0/cleo-agent_0.1.0_darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "0c7545f8d50416f8e06ec38052706e8aaf0a98d393b1bbbf5f6a07fea8654ef3"

      def install
        bin.install "cleo-agent"
      end
    end

    on_arm do
      url "https://github.com/meetcleo/cleo-agent/releases/download/v0.1.0/cleo-agent_0.1.0_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "faae321fb394a9b6dccfeff777c566dcd14ae2a17db83bc6a3cd44a69c63d060"

      def install
        bin.install "cleo-agent"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/meetcleo/cleo-agent/releases/download/v0.1.0/cleo-agent_0.1.0_linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "26640cd36c177d9e880ff8fa8ce1640f50b7180a7d04a89017774161bf32bb4b"

        def install
          bin.install "cleo-agent"
        end
      end
    end
  end
end
